lado1=float(input('digite o primeiro lado'))
lado2=float(input('digite o segundo lado'))
lado3=float(input('digite o terceiro lado'))
lado4=float(input('digite o quarto lado'))
somadoslados=float(lado1+lado2+lado3+lado4)
print("a soma dos lados do retângulo é:",(somadoslados))
